name: video_editor
version: 3.0.0
description: |
  A flutter package for editing video with fully customizable UI.
  Supports crop, trim, rotation and cover selection.
  Provides commands to run in order to export the video or cover.
repository: https://github.com/LeGoffMael/video_editor
environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: 1.9.0
  path_provider: 2.1.5
  transparent_image: 2.0.1 # show fade-in placeholder in thumbnails generation
  video_thumbnail: 0.5.3
  better_player_plus:
    git:
      url: https://github.com/PhantomRay/better_player_plus.git
      ref: 1137724be85732c109b37b588d9e610617e0b35e

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

screenshots:
  - description: "Video editor demo"
    path: assets/demo_thumb.webp
