name: video_editor
version: 3.0.0
description: |
  A flutter package for editing video with fully customizable UI.
  Supports crop, trim, rotation and cover selection.
  Provides commands to run in order to export the video or cover.
repository: https://github.com/LeGoffMael/video_editor
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  path_provider: 2.1.5
  transparent_image: 2.0.1
  video_player: ^2.9.2
  video_thumbnail:
    git:
      url: https://github.com/PhantomRay/video_thumbnail.git
      ref: 994ca82b5a59602652e2b5ab48bcb2ec3c4c0b8a

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

screenshots:
  - description: "Video editor demo"
    path: assets/demo_thumb.webp
